steps:
  # Passo 1: Constrói a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nome-do-seu-servico:latest', '.']

  # Passo 2: Envia a imagem para o Container Registry do Google
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nome-do-seu-servico:latest']

  # Passo 3: Faz o deploy da imagem para o Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'deploy-automatico-main'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nome-do-seu-servico:latest'
      - '--region'
      - 'southamerica-east1'