steps:
  # Passo 1: Compila a aplicação Java e cria o arquivo .jar
  - name: 'maven:3.9.6-eclipse-temurin-21-alpine'
    entrypoint: mvn
    args: ['package', '-DskipTests']
    
  # Passo 2: Constrói a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/deploy-automatico-main:latest', '.']
    
  # Passo 3: Envia a imagem para o Container Registry do Google
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/deploy-automatico-main:latest']
    
  # Passo 4: Faz o deploy da imagem para o Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'deploy-automatico-main'
      - '--image'
      - 'gcr.io/$PROJECT_ID/deploy-automatico-main:latest'
      - '--region'
      - 'southamerica-east1'
      - '--allow-unauthenticated' 

options:
  logging: CLOUD_LOGGING_ONLY